name: ABANDONED GROVE
tier: '1'
type: Exploration
description: A former druidic grove lying fallow and fully reclaimed by nature.
impulses: Draw in the curious, echo the past
difficulty: '11'
potential_adversaries: Beasts (Bear, Dire Wolf, Glass Snake), Grove Guardians (Minor
  Treant, Sylvan Soldier, Young Dryad)
feats:
- name: Overgrown Battlefield
  type: Passive
  text: |-
    There has been a battle here. A PC can make an Instinct Roll to identify evidence of that fight. On a success with Hope, learn all three pieces of information below. On a success with Fear, learn two. On a failure, a PC can mark 3 Stress to learn one and gain advantage on the next action roll to investigate this environment. A PC with an appropriate background or Experience can learn an additional detail and ask a follow-up question about the scene and get a truthful (if not always complete) answer.

      - Traces of a battle (broken weapons and branches, gouges in the ground) litter the ground.
      - A moss-covered tree trunk is actually the corpse of a treant.
      - Still-standing trees are twisted in strange ways, as if by powerful magic.
- name: Barbed Vines
  type: Action
  text: Pick a point within the grove. All targets within Very Close range of that
    point must succeed on an Agility Reaction Roll or take 1d8+3 physical damage
    and become Restrained by barbed vines. Restrained lasts until they’re freed with
    a successful Finesse or Strength roll or by dealing at least 6 damage to the
    vines.
- name: You Are Not Welcome Here
  type: Action
  text: A Young Dryad, two Sylvan Soldiers, and a number of Minor Treants equal to
    the number of PCs appear to confront the party for their intrusion.
- name: Defiler
  type: Action
  text: Spend a Fear to summon a Minor Chaos Adversary drawn to the echoes of violence
    and discord. They appear within Far range of a chosen PC and immediately take
    the spotlight.
layout: Daggerheart Environment
source: srd-environment
statblock: true